load:
  max_load: 0.9

memory:
  max_memory: 80.0
  max_swap: 70.0
  swap_enabled: false

disk:
  max_disk: 60.0
  paths:
    - /
    - /home
  ignore:
    - /boot/efi
  auto: false

systemd:
  enabled: false
